<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Form Submission #{{ $submission->id }}</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 14px;
            line-height: 1.5;
            color: #333;
        }
        .header {
            margin-bottom: 30px;
            border-bottom: 2px solid #eee;
            padding-bottom: 10px;
        }
        .header h1 {
            color: #2c3e50;
            margin: 0;
            font-size: 24px;
        }
        .meta {
            color: #7f8c8d;
            font-size: 12px;
            margin-top: 5px;
        }
        .section {
            margin-bottom: 20px;
        }
        .field-label {
            font-weight: bold;
            color: #34495e;
            display: block;
            margin-bottom: 3px;
        }
        .field-value {
            background: #f9f9f9;
            padding: 8px;
            border-radius: 4px;
            border: 1px solid #eee;
            word-wrap: break-word;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #95a5a6;
            border-top: 1px solid #eee;
            padding-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $form->name }}</h1>
        <div class="meta">
            Submission #{{ $submission->id }} • {{ $submission->created_at->format('M d, Y H:i A') }}
        </div>
    </div>

    <div class="content">
        @foreach($data as $key => $value)
            <div class="section">
                <span class="field-label">{{ ucwords(str_replace(['_', '-'], ' ', $key)) }}</span>
                <div class="field-value">
                    @if(is_array($value))
                        {{ implode(', ', $value) }}
                    @else
                        {{ $value }}
                    @endif
                </div>
            </div>
        @endforeach
    </div>

    <div class="footer">
        Generated by JA CMS on {{ now()->format('Y-m-d H:i:s') }}
        <br>
        IP: {{ $submission->ip_address }}
    </div>
</body>
</html>
