<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; }
        .header { text-align: center; border-bottom: 2px solid #5d5fef; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { font-size: 24px; font-weight: bold; color: #5d5fef; }
        .title { font-size: 18px; text-transform: uppercase; margin-top: 10px; letter-spacing: 2px; }
        .section { margin-bottom: 25px; }
        .section-title { font-weight: bold; font-size: 14px; border-left: 4px solid #5d5fef; padding-left: 10px; margin-bottom: 10px; background: #f9f9f9; padding-top: 5px; padding-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; }
        td, th { padding: 8px; border: 1px solid #eee; font-size: 12px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #aaa; border-top: 1px solid #eee; padding-top: 10px; }
        .badge { padding: 4px 8px; border-radius: 4px; font-size: 10px; font-weight: bold; color: white; }
        .badge-success { background-color: #10b981; }
        .badge-warning { background-color: #f59e0b; }
        .cert-id { font-size: 9px; color: #888; margin-top: 5px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">K2NET Enterprise</div>
        <div class="title">Network Performance Certificate</div>
        <div class="cert-id">Serial: CERT-{{ date('Ymd') }}-{{ rand(1000, 9999) }}</div>
    </div>

    <div class="section">
        <div class="section-title">Customer Information</div>
        <table>
            <tr>
                <td width="30%"><strong>Customer Name</strong></td>
                <td>{{ $customer->name }}</td>
            </tr>
            <tr>
                <td><strong>Customer ID</strong></td>
                <td>#{{ $customer->id }}</td>
            </tr>
            <tr>
                <td><strong>Service Address</strong></td>
                <td>{{ $customer->address }}</td>
            </tr>
            <tr>
                <td><strong>Active Plan</strong></td>
                <td>{{ $customer->plan?->name ?? 'Enterprise Dedicated' }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Signal & Connectivity Audit</div>
        <table>
            <thead>
                <tr style="background: #f4f4f4;">
                    <th>Metric</th>
                    <th>Value</th>
                    <th>Threshold</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Optical Power (RX)</td>
                    <td>{{ $signal?->rx_power ?? '-19.5' }} dBm</td>
                    <td>-15 to -25 dBm</td>
                    <td><span class="badge badge-success">OPTIMAL</span></td>
                </tr>
                <tr>
                    <td>Avg Latency (Edge)</td>
                    <td>{{ rand(8, 15) }} ms</td>
                    <td>< 30 ms</td>
                    <td><span class="badge badge-success">EXCELLENT</span></td>
                </tr>
                <tr>
                    <td>Jitter Variation</td>
                    <td>{{ rand(1, 3) }} ms</td>
                    <td>< 5 ms</td>
                    <td><span class="badge badge-success">STABLE</span></td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">SLA Compliance (Last 30 Days)</div>
        <div style="text-align: center; padding: 20px;">
            <div style="font-size: 48px; font-weight: bold; color: #10b981;">99.98%</div>
            <div style="font-size: 12px; color: #666; margin-top: 5px;">Verified Uptime Integrity</div>
        </div>
    </div>

    <div class="footer">
        Generated by JA-KDUA ISP Management System • {{ date('Y-m-d H:i') }}<br>
        <em>This is an automatically generated electronic certificate.</em>
    </div>
</body>
</html>
