import { Columns as ColumnsIcon } from 'lucide-vue-next';
import { defineAsyncComponent } from 'vue';

export default {
    name: 'columns',
    label: 'Columns',
    icon: ColumnsIcon,
    description: 'Create multi-column layouts.',
    component: defineAsyncComponent(() => import('@/components/builder/blocks/ColumnsBlock.vue')),
    settings: [
        {
            key: 'layout',
            type: 'toggle_group',
            label: 'Layout',
            options: [
                { label: '50/50', value: '1-1' },
                { label: '1/3 - 2/3', value: '1-2' },
                { label: '2/3 - 1/3', value: '2-1' },
                { label: '3 Cols', value: '1-1-1' }
            ],
            default: '1-1',
            tab: 'style'
        },
        // Legacy columns array (deprecated, use blocks)
        {
            key: 'columns',
            type: 'hidden',
            default: []
        },
        // Modern Child Blocks (Column objects)
        {
            key: 'blocks',
            type: 'hidden',
            default: []
        },
        {
            key: 'stackOn',
            type: 'select',
            label: 'Stack Columns On',
            options: [
                { label: 'Never', value: 'never' },
                { label: 'Mobile Only', value: 'sm' },
                { label: 'Mobile & Tablet', value: 'md' },
                { label: 'All Screens', value: 'lg' }
            ],
            default: 'never',
            tab: 'style'
        },
        {
            key: 'direction',
            type: 'toggle_group',
            label: 'Direction (Desktop)',
            options: [
                { label: '→', value: 'row' },
                { label: '←', value: 'row-reverse' },
                { label: '↓', value: 'column' },
                { label: '↑', value: 'column-reverse' }
            ],
            default: 'row',
            tab: 'style'
        },
        {
            key: 'mobileDirection',
            type: 'toggle_group',
            label: 'Direction (Mobile)',
            options: [
                { label: '→', value: 'row' },
                { label: '←', value: 'row-reverse' },
                { label: '↓', value: 'column' },
                { label: '↑', value: 'column-reverse' }
            ],
            default: 'column',
            condition: (settings) => settings.stackOn !== 'never',
            tab: 'style'
        },
        {
            key: 'width',
            type: 'select',
            label: 'Container Width',
            options: [
                { label: 'Standard', value: 'max-w-7xl' },
                { label: 'Full', value: 'max-w-full' }
            ],
            default: 'max-w-7xl',
            tab: 'style'
        },
        {
            key: 'gap',
            type: 'select',
            label: 'Gap',
            options: [
                { label: 'None', value: '0' },
                { label: 'Small (8px)', value: '2' },
                { label: 'Medium (16px)', value: '4' },
                { label: 'Large (32px)', value: '8' },
                { label: 'Generic (24px)', value: '6' },
                { label: 'XL (48px)', value: '12' },
            ],
            default: '8', // 2rem = 32px
            tab: 'style'
        },
        {
            key: 'padding',
            type: 'toggle_group',
            label: 'Padding',
            options: [
                { label: 'None', value: 'py-0' },
                { label: 'Md', value: 'py-16' },
                { label: 'Lg', value: 'py-24' }
            ],
            default: 'py-16',
            tab: 'style'
        },
        {
            key: 'bgColor',
            type: 'color',
            label: 'Background Color',
            default: 'transparent',
            tab: 'style'
        }
    ],
    defaultSettings: {
        layout: '1-1',
        columns: [], // Legacy
        customWidths: [50, 50],
        stackOn: 'never',
        gap: '8',
        direction: 'row',
        mobileDirection: 'column',
        padding: 'py-16',
        width: 'max-w-7xl',
        bgColor: 'transparent',
        radius: 'rounded-none',
        animation: '',
        blocks: [
            {
                id: 'default-col-1', // Will be regenerated by builder but useful for structure
                type: 'column',
                settings: { blocks: [] }
            },
            {
                id: 'default-col-2',
                type: 'column',
                settings: { blocks: [] }
            }
        ], // Modern
        visibility: { mobile: true, tablet: true, desktop: true }
    }
};
